### ISSUE TITLE
Code for native libraries

### ISSUE THREAD

**Issue by dalb8** [paolodongilli/SASAbus#1]
Can you please release the code for these libraries? Otherwise the app can't be distributed under the GPL license.

**Comment by paolodongilli** [comment]
Dear Dalb8,

thank you for your comment. To clarify what you state, the libs we 
included in our project are all licensed under the LGPL:
- mapsforge ( http://code.google.com/p/mapsforge/) --> LGPL 3 License
- zbar ( http://zbar.sourceforge.net/) --> LGPL 2.1 License
  -- libiconv.so libzbarjni.so are part of zbar

therefore we just need to include a notice regarding the license of 
these libraries and where the source code can be downloaded from.

Regards,
Paolo.

**Comment by dalb8** [comment]
Thats all I'm asking for, though it would be nice to include it in the repo and show how to build it with ndk.

**Comment by dalb8** [comment]
Obsqr is a project that uses zbar and it builds nicely with ndk. Also can you suggest Android SDK build target, for.those without the Intel one?

**Comment by dalb8** [comment]
Since there is no information about those files in libs/, I've had to take the app off F-droid.org. We often include jars that have well-documented origins, but we always look to build native libraries from source. Apologies for the inconvenience.

**Comment by paolodongilli** [comment]
```
Dear Dalb8,
  You could tell us you were referring to F-droid.org and how much
  time we had to complete the infos ...
  Regards,
  Paolo.
  On 25/11/2012 18:57, dalb8 wrote:

  Since there is no information about those files in libs/, I've
    had to take the app off F-droid.org. We often include jars that
    have well-known origins, but we always look to build native
    libraries from source. Apologies for the inconvenience.

    —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dalb8** [comment]
## There's no problem, if it's fixed it can go back in.

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by markuswindegger** [comment]
Ok, I was wondering why SASAbus was deleted on F-droid... :)

I think we can delete this libraries, because they were used in the v0.2.7 only, in v0.2.8 there is no more the QR-Code reader. There is no problem to delete the libraries. For mapsforge, there we must have the source or it's enough when we refer to the mapsforge project?

I think it's good that someone have informed us of these two thinks, because I personally do not know much about the licences.

~markus

**Comment by dalb8** [comment]
OK, I will add the latest version without zbar and iconv. It would have been enough to use the script that Obsqr uses that downloads zbar from Sourceforge. It will be sufficient to state where you got the mapsforge jar as well as the license I.e. the source code link is not as important. Also please state the android SDK target.

**Comment by markuswindegger** [comment]
I have created a Tag for you in my repository of SASAbus called "f_droid_v0.2.8.3", there is no libiconv, zbar.jar, etc...
And there are some bugs fixed, which in the google-play version are not fixed yet. The app propably runs on android 1.6+  too, but i haven't tested yet. It is tested from 2.1+.

Thank you again
~markus
